site_name: Global Institute for Macroprudential Modeling

theme:
    name: material
    logo: assets/gimm_m_rgb.png
    font: 
        code: "PT Mono"
        text: "Libre Baskerville"
    icon: 
        repo: fontawesome/brands/github
    palette:
        scheme: default
    features:
        - navigation.tabs
        - navigation.expand
        - navigation.indexes
    favicon: assets/favicon.ico

extra_css:
  - stylesheets/extra.css

docs_dir: source

site_dir: docs

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - Home: index.md
    - Upcoming events: 
        - events/index.md
        - Inaugural workkshop: events/inaugural.md

