site_name: Global Institute for Macroprudential Modeling

site_description: GIMM helps financial stability experts and macoprudential regulators meet, share knowledge, and implement state-of-the-art macroprudential modeling tool

theme:
    name: material
    logo: assets/gimm.yog.001.png
    font: 
        code: "PT Mono"
        text: "Libre Baskerville"
    icon: 
        repo: fontawesome/brands/github
    palette:
        scheme: default
    features:
        - navigation.tabs
        - navigation.expand
        - navigation.indexes
    favicon: assets/favicon.ico
    custom_dir: overrides

extra_css:
  - stylesheets/extra.css

docs_dir: source

site_dir: docs


repo_url: https://github.com/gimm-institute/member-zone
repo_name: Member zone

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences


nav:
    - Home: index.md
    - Membership: 
        - members/index.md
    - Upcoming events: 
        - events/inaugural.md
        - events/fall-2022.md
    - Know-how:
        - know-how/model.md
        - know-how/scenario-building.md
    - Global scenarios:
        - scenarios/index.md
        - scenarios/baseline.md
        - scenarios/stress.md
    - People behind:
        - people/index.md
    - Contact:
        - contact/index.md

